# syntax=docker/dockerfile:1.4
# Use an official Python runtime as a parent image
FROM python:3.10-slim

WORKDIR /usr/server

COPY ./src /usr/server

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]